name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  crypto: ^3.0.3
  mongo_dart: ^0.9.4
  http: ^1.2.1
  dart_firebase_admin: ^0.3.0
  uuid: ^3.0.4


dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
